/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tfg.Alta;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import tfg.BaseDeDatos;

/**
 *
 * @author Antonio
 */
public class Alta_Equipo extends javax.swing.JDialog {

    public Alta_Equipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(246, 244, 214));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Nombre = new javax.swing.JLabel();
        jButton_Anadir = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel_Estadio = new javax.swing.JLabel();
        jLabel_Ciudad = new javax.swing.JLabel();
        jLabel_Entrenador = new javax.swing.JLabel();
        jLabel_Presidente = new javax.swing.JLabel();
        jLabel_AnoFundacion = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Estadio = new javax.swing.JTextField();
        jTextField_Ciudad = new javax.swing.JTextField();
        jTextField_Entrenador = new javax.swing.JTextField();
        jTextField_Presidente = new javax.swing.JTextField();
        jTextField_AnoFundacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir equipo");

        jLabel_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Nombre.setText("Nombre");

        jButton_Anadir.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Anadir.setText("AÑADIR");
        jButton_Anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnadirActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Cancelar.setText("CANCELAR");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel_Estadio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Estadio.setText("Estadio");

        jLabel_Ciudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Ciudad.setText("Ciudad");

        jLabel_Entrenador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Entrenador.setText("Entrenador");

        jLabel_Presidente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Presidente.setText("Presidente");

        jLabel_AnoFundacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_AnoFundacion.setText("Año de fundación");

        jTextField_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_Estadio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_Ciudad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_Entrenador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_Presidente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_AnoFundacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Anadir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Nombre)
                            .addComponent(jLabel_Entrenador)
                            .addComponent(jLabel_Estadio)
                            .addComponent(jTextField_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jTextField_Entrenador)
                            .addComponent(jTextField_Estadio))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Presidente)
                            .addComponent(jLabel_AnoFundacion)
                            .addComponent(jLabel_Ciudad)
                            .addComponent(jTextField_Presidente)
                            .addComponent(jTextField_AnoFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Entrenador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Entrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Estadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Estadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_AnoFundacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_AnoFundacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Presidente)
                        .addGap(7, 7, 7)
                        .addComponent(jTextField_Presidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Ciudad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Anadir)
                    .addComponent(jButton_Cancelar))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private boolean hayError(String nombre, String campo) {
        if (campo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo " + nombre + " es obligatorio.", "Error", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        return false;
    }

    private void jButton_AnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnadirActionPerformed
        String nombre = jTextField_Nombre.getText();
        if (hayError("nombre", nombre)) {
            return;
        }

        //Comprueba si el equipo ya existe antes de añadirlo (solo compara el nombre)
        ArrayList consulta = BaseDeDatos.getBD().ConsultaSQL("SELECT idEquipo FROM equipo WHERE nombre='" + nombre + "'");
        if (!consulta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ya existe un equipo con el mismo nombre.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int anioFundacion;
        try {
            anioFundacion = Integer.parseInt(jTextField_AnoFundacion.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El año de fundación es incorrecto.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String entrenador = jTextField_Entrenador.getText();
        if (hayError("entrenador", entrenador)) {
            return;
        }
        String estadio = jTextField_Estadio.getText();
        if (hayError("estadio", estadio)) {
            return;
        }
        String ciudad = jTextField_Ciudad.getText();
        if (hayError("ciudad", ciudad)) {
            return;
        }
        String presidente = jTextField_Presidente.getText();

        BaseDeDatos.getBD().ConsultaSQL("INSERT INTO equipo OVERRIDING SYSTEM VALUE VALUES (null, '" + nombre + "', '" + estadio + "', " + anioFundacion + ", '" + ciudad + "', '" + entrenador + "', '" + presidente + "');");
        this.setVisible(false);
    }//GEN-LAST:event_jButton_AnadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Alta_Equipo dialog = new Alta_Equipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Anadir;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JLabel jLabel_AnoFundacion;
    private javax.swing.JLabel jLabel_Ciudad;
    private javax.swing.JLabel jLabel_Entrenador;
    private javax.swing.JLabel jLabel_Estadio;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Presidente;
    private javax.swing.JTextField jTextField_AnoFundacion;
    private javax.swing.JTextField jTextField_Ciudad;
    private javax.swing.JTextField jTextField_Entrenador;
    private javax.swing.JTextField jTextField_Estadio;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Presidente;
    // End of variables declaration//GEN-END:variables
}
