/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tfg.Alta;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import tfg.BaseDeDatos;

/**
 *
 * @author Antonio
 */
public class Alta_JugadorEquipo extends javax.swing.JDialog {

    int idCompeticion = -1;
    int idEquipo = -1;
    String fechaTraspaso;

    ArrayList datos = null;
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat formatoBD = new SimpleDateFormat("yyyy-MM-dd");

    public Alta_JugadorEquipo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public Alta_JugadorEquipo(java.awt.Frame parent, boolean modal, int idCompeticion, int idEquipo) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(246, 244, 214));
        this.idCompeticion = idCompeticion;
        this.idEquipo = idEquipo;
        cargarJugadores();
    }

    public void cargarJugadores() {
        DefaultComboBoxModel<String> dcbm = new DefaultComboBoxModel<>();
        String[] registro = null;
        datos = BaseDeDatos.getBD().ConsultaSQL("SELECT idJugador, nombre, apellido1, apellido2 FROM jugador");

        if (datos != null) {
            int n = datos.size();
            for (int i = 0; i < n; i++) {
                registro = (String[]) datos.get(i);
                dcbm.addElement(registro[1] + " " + registro[2] + " " + registro[3]);
            }
        }
        jComboBox_Jugadores.setModel(dcbm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_Jugadores = new javax.swing.JComboBox<>();
        jLabel_Jugadores = new javax.swing.JLabel();
        jButton_Anadir = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jLabel_FechaTraspaso = new javax.swing.JLabel();
        jTextField_FechaTraspaso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox_Jugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_Jugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel_Jugadores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Jugadores.setText("Jugadores");

        jButton_Anadir.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Anadir.setText("AÑADIR");
        jButton_Anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnadirActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Cancelar.setText("CANCELAR");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jLabel_FechaTraspaso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_FechaTraspaso.setText("Fecha de incorporación");

        jTextField_FechaTraspaso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Anadir))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Jugadores)
                            .addComponent(jComboBox_Jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_FechaTraspaso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_FechaTraspaso))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Jugadores)
                    .addComponent(jLabel_FechaTraspaso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_FechaTraspaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Anadir)
                    .addComponent(jButton_Cancelar))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnadirActionPerformed
        try {
            Date fecha = formato.parse(jTextField_FechaTraspaso.getText());
            fechaTraspaso = formatoBD.format(fecha);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "El formato de la fecha de trapaso no es correcto. Debe ser 'dd/mm/aaaa'.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String[] registro = (String[]) datos.get(jComboBox_Jugadores.getSelectedIndex());
        int idJugador = Integer.parseInt(registro[0]);

        //Comprueba si el jugador ya pertenece al equipo antes de añadirlo
        ArrayList consulta = BaseDeDatos.getBD().ConsultaSQL("SELECT idJugador FROM pertenece WHERE (idCompeticion=" + idCompeticion + ") AND (idEquipo=" + idEquipo + ") AND (idJugador=" + idJugador + ")");
        if (!consulta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El jugador ya pertenece a este equipo en esta competición.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        BaseDeDatos.getBD().ConsultaSQL("INSERT INTO pertenece VALUES (" + idJugador + ", " + idEquipo + ", " + idCompeticion + ", '" + fechaTraspaso + "');");
        this.setVisible(false);
    }//GEN-LAST:event_jButton_AnadirActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta_JugadorEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta_JugadorEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta_JugadorEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta_JugadorEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Alta_JugadorEquipo dialog = new Alta_JugadorEquipo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Anadir;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JComboBox<String> jComboBox_Jugadores;
    private javax.swing.JLabel jLabel_FechaTraspaso;
    private javax.swing.JLabel jLabel_Jugadores;
    private javax.swing.JTextField jTextField_FechaTraspaso;
    // End of variables declaration//GEN-END:variables
}
