/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tfg.InfoModificar;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import misqlhsqldb.MiSQLhSQLDB;

/**
 *
 * @author Antonio
 */
public class InfoModificar_Competicion extends javax.swing.JDialog {
    private class miTablaModel extends DefaultTableModel{
        public boolean isCellEditable (int row, int column){
            return false;
        }
    }
    
    MiSQLhSQLDB bbdd = new MiSQLhSQLDB("SA", "SA");
    ArrayList datosTemporada = null;
    ArrayList datosLiga = null;
    ArrayList datosCompeticion = null;
    ArrayList datosEquipos = null;
    int idCompeticion;
    
    public InfoModificar_Competicion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public InfoModificar_Competicion(java.awt.Frame parent, boolean modal, int idCompeticion){
        super(parent, modal);
        initComponents();
        this.idCompeticion = idCompeticion;
        cargarTemporadas();
        cargarLigas();
        cargarTabla();
    }
    
    public void cargarTemporadas(){
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        String[] registro = null;
        datosTemporada = bbdd.ConsultaSQL("SELECT idTemporada, anio FROM temporada;");
        
        if(datosTemporada != null){
            int n = datosTemporada.size();
            for(int i=0; i<n; i++){
                registro = (String[]) datosTemporada.get(i);
                dcbm.addElement(registro[1]);
            }
        }
        jComboBox_Temporadas.setModel(dcbm);
    }
    
    public void cargarLigas(){
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        String[] registro = null;
        datosLiga = bbdd.ConsultaSQL("SELECT idLiga, nombre FROM liga;");
        
        if(datosLiga != null){
            int n = datosLiga.size();
            for(int i=0; i<n; i++){
                registro = (String[]) datosLiga.get(i);
                dcbm.addElement(registro[1]);
            }
        }
        jComboBox_Ligas.setModel(dcbm);
    }
    
    //MIRAR
    public void mostrarTemporadaLigaActual(){
        String[] registro = null;
        datosCompeticion = bbdd.ConsultaSQL("SELECT idTemporada, idLiga FROM competicion WHERE idCompeticion = " +idCompeticion +";");
        jComboBox_Temporadas.setSelectedIndex(Integer.parseInt(registro[0]));
        jComboBox_Ligas.setSelectedIndex(Integer.parseInt(registro[1]));
    }
    
    public void cargarTabla(){
        String[] registro = null;
        
        miTablaModel dtm = new miTablaModel();
        dtm.addColumn("Nombre");
        dtm.addColumn("Estadio");
        dtm.addColumn("Año de fundación");
        dtm.addColumn("Ciudad");
        dtm.addColumn("Entrenador");
        dtm.addColumn("Presidente");
        
        datosEquipos = bbdd.ConsultaSQL("SELECT E.nombre, E.estadio, E.anioFundacion, E.ciudad, E.entrenador, E.presidente FROM equipo E, compite C WHERE (C.idEquipo = E.idEquipo) AND (C.idCompeticion = " +idCompeticion +");");

        if(datosEquipos != null){
            int n = datosEquipos.size();
            for(int i = 0; i < n; i++){
                registro = (String[]) datosEquipos.get(i);
                Object[] fila = new Object[]{
                    registro[0],
                    registro[1],
                    registro[2],
                    registro[3],
                    registro[4],
                    registro[5]
                };
                dtm.addRow(fila); 
            }
        }
        jTable_Equipos.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Temporada = new javax.swing.JLabel();
        jLabel_Liga = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jComboBox_Temporadas = new javax.swing.JComboBox<>();
        jComboBox_Ligas = new javax.swing.JComboBox<>();
        jTextField_Nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Equipos = new javax.swing.JTable();
        jLabel_Equipos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_Temporada.setText("Temporada");

        jLabel_Liga.setText("Liga");

        jLabel_Nombre.setText("Nombre");

        jComboBox_Temporadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox_Ligas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable_Equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Equipos);

        jLabel_Equipos.setText("Equipos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_Temporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Temporada))
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Liga)
                        .addGap(253, 253, 253)
                        .addComponent(jLabel_Nombre)
                        .addGap(257, 257, 257))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_Ligas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Equipos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Temporada)
                    .addComponent(jLabel_Liga)
                    .addComponent(jLabel_Nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Temporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Ligas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jLabel_Equipos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoModificar_Competicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoModificar_Competicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoModificar_Competicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoModificar_Competicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InfoModificar_Competicion dialog = new InfoModificar_Competicion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_Ligas;
    private javax.swing.JComboBox<String> jComboBox_Temporadas;
    private javax.swing.JLabel jLabel_Equipos;
    private javax.swing.JLabel jLabel_Liga;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Temporada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Equipos;
    private javax.swing.JTextField jTextField_Nombre;
    // End of variables declaration//GEN-END:variables
}
