/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tfg.InfoModificar;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import tfg.BaseDeDatos;

/**
 *
 * @author Antonio
 */
public class Modificar_Jugador extends javax.swing.JDialog {

    private static final SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    private static final SimpleDateFormat formatoBD = new SimpleDateFormat("yyyy-MM-dd");

    int id = -1;

    public Modificar_Jugador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(214, 239, 246));
    }

    public Modificar_Jugador(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(new Color(214, 239, 246));
        this.id = id;
        cargarDatos();
    }

    public void cargarDatos() {
        ArrayList datos = BaseDeDatos.getBD().ConsultaSQL("SELECT nombre, apellido1, apellido2, dorsal, fechaNacimiento, posicion, pais\n"
                + "FROM jugador WHERE idJugador = '" + id + "'");

        String[] registro = (String[]) datos.get(0);
        jTextField_Nombre.setText(registro[0]);
        jTextField_Apellido1.setText(registro[1]);
        jTextField_Apellido2.setText(registro[2]);
        jTextField_Dorsal.setText(registro[3]);
        try {
            Date fecha = formatoBD.parse(registro[4]);
            registro[4] = formato.format(fecha);
        } catch (ParseException ex) {
        }
        jTextField_FechaNacimiento.setText(registro[4]);
        jTextField_Posicion.setText(registro[5]);
        jTextField_Pais.setText(registro[6]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Apellido1 = new javax.swing.JTextField();
        jLabel_Pais = new javax.swing.JLabel();
        jTextField_Apellido2 = new javax.swing.JTextField();
        jTextField_Dorsal = new javax.swing.JTextField();
        jLabel_Apellido1 = new javax.swing.JLabel();
        jLabel_Apellido2 = new javax.swing.JLabel();
        jLabel_Dorsal = new javax.swing.JLabel();
        jTextField_FechaNacimiento = new javax.swing.JTextField();
        jLabel_FechaNacimiento = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jTextField_Posicion = new javax.swing.JTextField();
        jLabel_Posicion = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Pais = new javax.swing.JTextField();
        jButton_Guardar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField_Apellido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_Pais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Pais.setText("País");

        jTextField_Apellido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_Dorsal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_Apellido1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Apellido1.setText("Primer apellido");

        jLabel_Apellido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Apellido2.setText("Segundo apellido");

        jLabel_Dorsal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Dorsal.setText("Dorsal");

        jTextField_FechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_FechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_FechaNacimiento.setText("Fecha de nacimiento");

        jLabel_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Nombre.setText("Nombre");

        jTextField_Posicion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_Posicion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_Posicion.setText("Posición");

        jTextField_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_Pais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton_Guardar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Guardar.setText("GUARDAR");
        jButton_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GuardarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Cancelar.setText("CANCELAR");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_FechaNacimiento)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_Apellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(jLabel_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Apellido1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Apellido1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Pais)
                                .addComponent(jLabel_Posicion)
                                .addComponent(jTextField_Posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel_Dorsal)
                                    .addGap(86, 86, 86))
                                .addComponent(jTextField_FechaNacimiento)
                                .addComponent(jTextField_Dorsal)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_Cancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_Guardar)))
                    .addComponent(jLabel_Apellido2))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nombre)
                    .addComponent(jLabel_FechaNacimiento)
                    .addComponent(jLabel_Pais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Apellido1)
                    .addComponent(jLabel_Dorsal)
                    .addComponent(jLabel_Posicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Dorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_Apellido2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Guardar)
                    .addComponent(jButton_Cancelar))
                .addGap(244, 244, 244))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean hayError(String nombre, String campo) {
        if (campo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo " + nombre + " es obligatorio.", "Error", JOptionPane.WARNING_MESSAGE);
            return true;
        }
        return false;
    }

    private void jButton_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GuardarActionPerformed
        String nombre = jTextField_Nombre.getText();
        if (hayError("nombre", nombre)) {
            return;
        }
        String apellido1 = jTextField_Apellido1.getText();
        if (hayError("primer apellido", apellido1)) {
            return;
        }
        String apellido2 = jTextField_Apellido2.getText();
        if (hayError("segundo apellido", apellido2)) {
            return;
        }
        String pais = jTextField_Pais.getText();
        if (hayError("país", pais)) {
            return;
        }
        String posicion = jTextField_Posicion.getText();
        if (hayError("posición", posicion)) {
            return;
        }
        String fechaNacimiento;
        try {
            Date fecha = formato.parse(jTextField_FechaNacimiento.getText());
            fechaNacimiento = formatoBD.format(fecha);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "El formato de la fecha de nacimiento no es correcto. Debe ser 'dd/mm/aaaa'.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int dorsal;
        try {
            dorsal = Integer.parseInt(jTextField_Dorsal.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "El dorsal es incorrecto.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Todo ha ido bien y actualiza el jugador en la base de datos y finaliza el modo modificación
        BaseDeDatos.getBD().ConsultaSQL("UPDATE jugador SET nombre = '" + nombre + "', apellido1 = '" + apellido1 + "', apellido2 = '" + apellido2 + "', dorsal = " + dorsal + ", fechaNacimiento = '" + fechaNacimiento + "', posicion = '" + posicion + "', pais = '" + pais + "' WHERE idJugador = " + id);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_GuardarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modificar_Jugador dialog = new Modificar_Jugador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JButton jButton_Guardar;
    private javax.swing.JLabel jLabel_Apellido1;
    private javax.swing.JLabel jLabel_Apellido2;
    private javax.swing.JLabel jLabel_Dorsal;
    private javax.swing.JLabel jLabel_FechaNacimiento;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Pais;
    private javax.swing.JLabel jLabel_Posicion;
    private javax.swing.JTextField jTextField_Apellido1;
    private javax.swing.JTextField jTextField_Apellido2;
    private javax.swing.JTextField jTextField_Dorsal;
    private javax.swing.JTextField jTextField_FechaNacimiento;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Pais;
    private javax.swing.JTextField jTextField_Posicion;
    // End of variables declaration//GEN-END:variables
}
