/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tfg;

import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import tfg.Alta.Alta_Equipo;
import tfg.InfoModificar.InfoModificar_Equipo;

public class Equipos extends javax.swing.JPanel {

    private class miTablaModel extends DefaultTableModel {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }

    ArrayList datos = null;

    int id = -1;

    public Equipos() {
        initComponents();
        estiloJLabel();
        estiloJTable();
        cargarTabla();
        estadoBotones();
    }

    public void estiloJLabel() {
        jLabel_Equipos.setFont(new Font("Segoe UI", Font.BOLD, 50));
        jLabel_Equipos.setOpaque(true);
    }

    public void estiloJTable() {
        JTableHeader header = jTable_Equipos.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 16));
        jTable_Equipos.setFillsViewportHeight(true); // para que el fondo se use en todo
    }

    public void estadoBotones() {
        boolean habilitado = jTable_Equipos.getSelectedRow() != -1;
        jButton_InfoModificar.setEnabled(habilitado);
        jButton_Eliminar.setEnabled(habilitado);
    }

    public void cargarTabla() {
        miTablaModel dtm = new miTablaModel();
        dtm.addColumn("Nombre");
        dtm.addColumn("Estadio");
        dtm.addColumn("Año de fundación");
        dtm.addColumn("Ciudad");
        dtm.addColumn("Entrenador");
        dtm.addColumn("Presidente");

        datos = BaseDeDatos.getBD().ConsultaSQL("SELECT idEquipo, nombre, estadio, anioFundacion, ciudad, entrenador, presidente\n"
                + "FROM equipo");

        if (datos != null) {
            int n = datos.size();
            for (int i = 0; i < n; i++) {
                String[] registro = (String[]) datos.get(i);
                Object[] fila = new Object[]{
                    registro[1],
                    registro[2],
                    registro[3],
                    registro[4],
                    registro[5],
                    registro[6]
                };
                dtm.addRow(fila);
            }
        }

        jTable_Equipos.setModel(dtm);
    }

    private void masInformacion() {
        String[] registro = (String[]) datos.get(jTable_Equipos.getSelectedRow());
        id = Integer.parseInt(registro[0]);

        InfoModificar_Equipo ventana = new InfoModificar_Equipo((JFrame) this.getRootPane().getParent(), true, id);
        ventana.setSize(new Dimension(1000, 700));
        ventana.setLocationRelativeTo(null);
        ventana.setModal(true);
        ventana.setVisible(true);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel_Equipos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Equipos = new javax.swing.JTable();
        jButton_Crear = new javax.swing.JButton();
        jButton_InfoModificar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 242));
        setLayout(new java.awt.GridBagLayout());

        jLabel_Equipos.setBackground(new java.awt.Color(246, 244, 214));
        jLabel_Equipos.setForeground(new java.awt.Color(152, 156, 44));
        jLabel_Equipos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Equipos.setText("Equipos");
        jLabel_Equipos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 16, 8, 0));
        jLabel_Equipos.setMaximumSize(new java.awt.Dimension(2300, 300));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jLabel_Equipos, gridBagConstraints);

        jTable_Equipos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable_Equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Equipos.setRowHeight(24);
        jTable_Equipos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_Equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_EquiposMouseClicked(evt);
            }
        });
        jTable_Equipos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable_EquiposPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Equipos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        add(jScrollPane1, gridBagConstraints);

        jButton_Crear.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Crear.setText("CREAR NUEVO");
        jButton_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 48, 0);
        add(jButton_Crear, gridBagConstraints);

        jButton_InfoModificar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_InfoModificar.setText("CONSULTAR / MODIFICAR");
        jButton_InfoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InfoModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 48, 0);
        add(jButton_InfoModificar, gridBagConstraints);

        jButton_Eliminar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Eliminar.setText("ELIMINAR");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 48, 0);
        add(jButton_Eliminar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearActionPerformed
        Alta_Equipo ventana = new Alta_Equipo((JFrame) this.getRootPane().getParent(), true);
        ventana.setTitle("Nuevo equipo");
        ventana.setSize(new Dimension(450, 350));
        ventana.setLocationRelativeTo(null);
        ventana.setModal(true);
        ventana.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_jButton_CrearActionPerformed

    private void jTable_EquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_EquiposMouseClicked
        if (evt.getClickCount() == 1) {
            estadoBotones();
        }
        if (evt.getClickCount() == 2) {
            masInformacion();
        }
    }//GEN-LAST:event_jTable_EquiposMouseClicked

    private void jButton_InfoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InfoModificarActionPerformed
        masInformacion();
    }//GEN-LAST:event_jButton_InfoModificarActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        String[] registro = (String[]) datos.get(jTable_Equipos.getSelectedRow());
        id = Integer.parseInt(registro[0]);

        ArrayList numeroCompeticiones = BaseDeDatos.getBD().ConsultaSQL("SELECT COUNT(*) FROM compite WHERE idEquipo=" + id);
        registro = (String[]) numeroCompeticiones.get(0);
        if (Integer.parseInt(registro[0]) > 0) {
            JOptionPane.showMessageDialog(this, "No se puede borrar este equipo porque pertenece a alguna competición.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int respuesta = JOptionPane.showOptionDialog(this, "¿Seguro que quiere eliminar este equipo?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, new Object[]{"SÍ", "NO"}, "NO");
        if (respuesta == 0) {
            //Se borra la pertencia de los jugadores de todos los equipos de la competición
            BaseDeDatos.getBD().ConsultaSQL("DELETE FROM pertenece WHERE idEquipo = " + id);
            //Se borra la clasificación de todos los equipos de la competición
            BaseDeDatos.getBD().ConsultaSQL("DELETE FROM clasifica WHERE idEquipo = " + id);
            //Se borra el equipo
            BaseDeDatos.getBD().ConsultaSQL("DELETE FROM equipo WHERE idEquipo = " + id);
            cargarTabla();
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jTable_EquiposPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable_EquiposPropertyChange
        estadoBotones();
    }//GEN-LAST:event_jTable_EquiposPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Crear;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_InfoModificar;
    private javax.swing.JLabel jLabel_Equipos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Equipos;
    // End of variables declaration//GEN-END:variables
}
