/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tfg;

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JScrollPane;

/**
 *
 * @author Antonio
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    Temporadas panelTemporadas = new Temporadas();
    Ligas panelLigas = new Ligas();
    Competiciones panelCompeticiones = new Competiciones();
    Equipos panelEquipos = new Equipos();
    Principal panelPrincipal = new Principal();
    JScrollPane scrollpane;
    Component uno;
    
    public Inicio() {
        initComponents();
        java.awt.GridBagConstraints gridBagConstraints;
        establecerIconos();
        
        scrollpane = new JScrollPane();
        scrollpane.setBounds(panelPrincipal.getX(), panelPrincipal.getY(), panelPrincipal.getWidth(), panelPrincipal.getHeight());
        this.setExtendedState(MAXIMIZED_BOTH);
        
        getContentPane().remove(jPanel2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 100.0;
        uno = panelPrincipal;
        //getContentPane().add(panelPrincipal, gridBagConstraints);
        //panelPrincipal.setVisible(true);
        
        scrollpane.setViewportView(panelPrincipal);
        add(scrollpane, gridBagConstraints);
        //this.getContentPane().add(panelPrincipal);
        //panelPrincipal.setVisible(true);
        //panel.setBounds(500,500,100,100);
    }
    
    public void establecerIconos(){
        jButton_Inicio.setIcon(new ImageIcon("src/imagenes/casa1 (1).png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton_Inicio = new javax.swing.JButton();
        jButton_Temporadas = new javax.swing.JButton();
        jButton_Ligas = new javax.swing.JButton();
        jButton_Competiciones = new javax.swing.JButton();
        jButton_Equipos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fútbol");
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 40));

        jButton_Inicio.setBackground(new java.awt.Color(153, 204, 255));
        jButton_Inicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Inicio.setText("Inicio");
        jButton_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InicioActionPerformed(evt);
            }
        });

        jButton_Temporadas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Temporadas.setText("Temporadas");
        jButton_Temporadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TemporadasActionPerformed(evt);
            }
        });

        jButton_Ligas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Ligas.setText("Ligas");
        jButton_Ligas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LigasActionPerformed(evt);
            }
        });

        jButton_Competiciones.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Competiciones.setText("Competiciones");
        jButton_Competiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CompeticionesActionPerformed(evt);
            }
        });

        jButton_Equipos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Equipos.setText("Equipos");
        jButton_Equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton_Inicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Temporadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Ligas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Competiciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Equipos)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Temporadas)
                        .addComponent(jButton_Ligas)
                        .addComponent(jButton_Competiciones)
                        .addComponent(jButton_Equipos))
                    .addComponent(jButton_Inicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InicioActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelPrincipal);
    }//GEN-LAST:event_jButton_InicioActionPerformed

    private void jButton_TemporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TemporadasActionPerformed
        /*JDialog ventana = new JDialog();
        ventana.setTitle("Nueva temporada");
        ventana.setSize(new Dimension(1000, 700));
        ventana.setLocationRelativeTo(null);
        ventana.setModal(true);
        ventana.add(panelTemporadas);
        ventana.setVisible(true);*/
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelTemporadas);
    }//GEN-LAST:event_jButton_TemporadasActionPerformed

    private void jButton_LigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LigasActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelLigas);
    }//GEN-LAST:event_jButton_LigasActionPerformed

    private void jButton_CompeticionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CompeticionesActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelCompeticiones);
    }//GEN-LAST:event_jButton_CompeticionesActionPerformed

    private void jButton_EquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EquiposActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelEquipos);
    }//GEN-LAST:event_jButton_EquiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Competiciones;
    private javax.swing.JButton jButton_Equipos;
    private javax.swing.JButton jButton_Inicio;
    private javax.swing.JButton jButton_Ligas;
    private javax.swing.JButton jButton_Temporadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
