/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tfg;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;

/**
 *
 * @author Antonio
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    static Principal principal;
    static Competiciones competiciones;

    Principal panelPrincipal = new Principal();
    Temporadas panelTemporadas = new Temporadas();
    Ligas panelLigas = new Ligas();
    Competiciones panelCompeticiones = new Competiciones();
    Equipos panelEquipos = new Equipos();
    Jugadores panelJugadores = new Jugadores();

    JScrollPane scrollpane;

    static public void temporadaModificada() {
        principal.temporadaModificada();
        competiciones.temporadaLigaModificada();
    }

    static public void ligaModificada() {
        principal.ligaModificada();
        competiciones.temporadaLigaModificada();
    }

    static public void competicionModificada() {
        principal.competicionModificada();
    }

    public Inicio() {
        initComponents();
        java.awt.GridBagConstraints gridBagConstraints;
        establecerIconos();

        principal = panelPrincipal;
        competiciones = panelCompeticiones;

        scrollpane = new JScrollPane();
        scrollpane.setBounds(panelPrincipal.getX(), panelPrincipal.getY(), panelPrincipal.getWidth(), panelPrincipal.getHeight());
        this.setExtendedState(MAXIMIZED_BOTH);

        getContentPane().remove(jPanel2);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 100.0;

        scrollpane.setViewportView(panelPrincipal);
        add(scrollpane, gridBagConstraints);
    }

    private ImageIcon icono32x32(String url) {
        Image imagen = new ImageIcon(getClass().getClassLoader().getResource(url)).getImage();
        return new ImageIcon(imagen.getScaledInstance(32, 32, java.awt.Image.SCALE_SMOOTH));
    }

    public void establecerIconos() {
        //Cambia el icono de la aplicación
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("imagenes/icono.png")).getImage());

        //Cambia los iconos de los botones principales
        jButton_Inicio.setIcon(icono32x32("imagenes/inicio.png"));
        jButton_Temporadas.setIcon(icono32x32("imagenes/temporadas.png"));
        jButton_Ligas.setIcon(icono32x32("imagenes/icono.png"));
        jButton_Competiciones.setIcon(icono32x32("imagenes/competiciones.png"));
        jButton_Equipos.setIcon(icono32x32("imagenes/equipos.png"));
        jButton_Jugadores.setIcon(icono32x32("imagenes/jugadores.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButton_Inicio = new javax.swing.JButton();
        jButton_Temporadas = new javax.swing.JButton();
        jButton_Ligas = new javax.swing.JButton();
        jButton_Competiciones = new javax.swing.JButton();
        jButton_Equipos = new javax.swing.JButton();
        jButton_Jugadores = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("League Manager");
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 224));
        jPanel1.setMaximumSize(new java.awt.Dimension(300, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 80));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 16, 18));

        jButton_Inicio.setBackground(new java.awt.Color(178, 216, 255));
        jButton_Inicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Inicio.setText("Inicio");
        jButton_Inicio.setIconTextGap(12);
        jButton_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InicioActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Inicio);

        jButton_Temporadas.setBackground(new java.awt.Color(178, 216, 255));
        jButton_Temporadas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Temporadas.setText("Temporadas");
        jButton_Temporadas.setIconTextGap(12);
        jButton_Temporadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TemporadasActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Temporadas);

        jButton_Ligas.setBackground(new java.awt.Color(178, 216, 255));
        jButton_Ligas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Ligas.setText("Ligas");
        jButton_Ligas.setIconTextGap(12);
        jButton_Ligas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LigasActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Ligas);

        jButton_Competiciones.setBackground(new java.awt.Color(178, 216, 255));
        jButton_Competiciones.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Competiciones.setText("Competiciones");
        jButton_Competiciones.setIconTextGap(12);
        jButton_Competiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CompeticionesActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Competiciones);

        jButton_Equipos.setBackground(new java.awt.Color(178, 216, 255));
        jButton_Equipos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Equipos.setText("Equipos");
        jButton_Equipos.setIconTextGap(12);
        jButton_Equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EquiposActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Equipos);

        jButton_Jugadores.setBackground(new java.awt.Color(178, 216, 255));
        jButton_Jugadores.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton_Jugadores.setText("Jugadores");
        jButton_Jugadores.setIconTextGap(12);
        jButton_Jugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_JugadoresActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Jugadores);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InicioActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelPrincipal);
    }//GEN-LAST:event_jButton_InicioActionPerformed

    private void jButton_TemporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TemporadasActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelTemporadas);
    }//GEN-LAST:event_jButton_TemporadasActionPerformed

    private void jButton_LigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LigasActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelLigas);
    }//GEN-LAST:event_jButton_LigasActionPerformed

    private void jButton_CompeticionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CompeticionesActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelCompeticiones);
    }//GEN-LAST:event_jButton_CompeticionesActionPerformed

    private void jButton_EquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EquiposActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelEquipos);
    }//GEN-LAST:event_jButton_EquiposActionPerformed

    private void jButton_JugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_JugadoresActionPerformed
        getContentPane().remove(jPanel2);
        java.awt.GridBagConstraints gridBagConstraints;
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        scrollpane.setViewportView(panelJugadores);
    }//GEN-LAST:event_jButton_JugadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Competiciones;
    private javax.swing.JButton jButton_Equipos;
    private javax.swing.JButton jButton_Inicio;
    private javax.swing.JButton jButton_Jugadores;
    private javax.swing.JButton jButton_Ligas;
    private javax.swing.JButton jButton_Temporadas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
