/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tfg;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import misqlhsqldb.MiSQLhSQLDB;
import tfg.Alta.Alta_Jugador;

import static tfg.BaseDeDatos.conectarBD;
import tfg.InfoModificar.InfoModificar_Jugador;

/**
 *
 * @author Antonio
 */
public class Jugadores extends javax.swing.JPanel {
    private class miTablaModel extends DefaultTableModel{
        public boolean isCellEditable (int row, int column){
            return false;
        }
    }
    
    ArrayList datos = null;
    MiSQLhSQLDB bbdd = new MiSQLhSQLDB("SA", "SA");
    
    private int id = -1;
    
    public Jugadores() {
        initComponents();
        conectarBD();
        estiloJLabel();
        cargarTabla();
        jButton_InfoModificar.setEnabled(false);
        jButton_Eliminar.setEnabled(false);
    }
    
    public void estiloJLabel(){
        jLabel_Jugadores.setFont(new Font("Verdana", 0, 50));
        jLabel_Jugadores.setOpaque(true);
        jLabel_Jugadores.setBackground(Color.yellow);
    }
    
    public void cargarTabla(){
        String[] registro = null;
        
        miTablaModel dtm = new miTablaModel();
        dtm.addColumn("ID");
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellidos");
        dtm.addColumn("Fecha de nacimiento");
        dtm.addColumn("Dorsal");
        dtm.addColumn("Posición");
        dtm.addColumn("País");
                
        datos = bbdd.ConsultaSQL("SELECT idJugador, nombre, apellido1, apellido2, fechaNacimiento, dorsal, posicion, pais\n" +
        "FROM jugador");
        
        if(datos != null){
            int n = datos.size();
            for(int i = 0; i < n; i++){
                registro = (String[]) datos.get(i);
                Object[] fila = new Object[]{
                    registro[0],
                    registro[1],
                    registro[2] +" " +registro[3],
                    registro[4],
                    registro[5],
                    registro[6],
                    registro[7]
                };
                dtm.addRow(fila); 
            }
        }
        
        jTable_Jugadores.setModel(dtm);
    }
    
    private void masInformacion(){
        String[] registro = (String[]) datos.get(jTable_Jugadores.getSelectedRow());
        id = Integer.parseInt(registro[0]);
        
        InfoModificar_Jugador ventana =  new InfoModificar_Jugador((JFrame) this.getRootPane().getParent(), true, id);
        ventana.setTitle("Información jugador");
        ventana.setSize(new Dimension(1000, 700));
        ventana.setLocationRelativeTo(null);
        ventana.setModal(true);
        ventana.setVisible(true);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Jugadores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Jugadores = new javax.swing.JTable();
        jButton_Crear = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_InfoModificar = new javax.swing.JButton();

        jLabel_Jugadores.setBackground(new java.awt.Color(255, 255, 51));
        jLabel_Jugadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Jugadores.setText("Jugadores");
        jLabel_Jugadores.setMaximumSize(new java.awt.Dimension(2300, 300));

        jTable_Jugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Jugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_JugadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Jugadores);

        jButton_Crear.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Crear.setText("CREAR NUEVO");
        jButton_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearActionPerformed(evt);
            }
        });

        jButton_Eliminar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Eliminar.setText("ELIMINAR");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });

        jButton_InfoModificar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_InfoModificar.setText("MÁS INFORMACIÓN");
        jButton_InfoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InfoModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Crear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_InfoModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Eliminar)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Jugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Crear)
                    .addComponent(jButton_InfoModificar)
                    .addComponent(jButton_Eliminar))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_JugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_JugadoresMouseClicked
        if(evt.getClickCount()==1){
            jButton_InfoModificar.setEnabled(true);
            jButton_Eliminar.setEnabled(true);
        }
        if(evt.getClickCount()==2){
            masInformacion();
        }
    }//GEN-LAST:event_jTable_JugadoresMouseClicked

    private void jButton_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearActionPerformed
        Alta_Jugador ventana =  new Alta_Jugador ((JFrame) this.getRootPane().getParent(), true);
        ventana.setTitle("Nuevo jugador");
        ventana.setSize(new Dimension(700, 500));
        ventana.setLocationRelativeTo(null);
        ventana.setModal(true);
        ventana.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_jButton_CrearActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        String[] registro = (String[]) datos.get(jTable_Jugadores.getSelectedRow());
        id = Integer.parseInt(registro[0]);
        datos = bbdd.ConsultaSQL("DELETE FROM jugador WHERE idJugador = '" +id +"'");
        cargarTabla();
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_InfoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InfoModificarActionPerformed
        masInformacion();
    }//GEN-LAST:event_jButton_InfoModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Crear;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_InfoModificar;
    private javax.swing.JLabel jLabel_Jugadores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Jugadores;
    // End of variables declaration//GEN-END:variables
}
