/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tfg;

import java.awt.Dimension;
import java.awt.Font;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import tfg.Alta.Alta_Jugador;
import tfg.InfoModificar.Modificar_Jugador;

/**
 *
 * @author Antonio
 */
public class Jugadores extends javax.swing.JPanel {

    private static final SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    private static final SimpleDateFormat formatoBD = new SimpleDateFormat("yyyy-MM-dd");

    private class miTablaModel extends DefaultTableModel {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }

    ArrayList datos = null;

    private int id = -1;

    public Jugadores() {
        initComponents();
        estiloJLabel();
        estiloJTable();
        cargarTabla();
        estadoBotones();
    }

    public void estiloJLabel() {
        jLabel_Jugadores.setFont(new Font("Segoe UI", Font.BOLD, 50));
        jLabel_Jugadores.setOpaque(true);
    }

    public void estiloJTable() {
        JTableHeader header = jTable_Jugadores.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 16));
        jTable_Jugadores.setFillsViewportHeight(true); // para que el fondo se use en todo
    }

    public void estadoBotones() {
        boolean habilitado = jTable_Jugadores.getSelectedRow() != -1;
        jButton_Modificar.setEnabled(habilitado);
        jButton_Eliminar.setEnabled(habilitado);
    }

    public void cargarTabla() {
        String[] registro = null;

        miTablaModel dtm = new miTablaModel();
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellidos");
        dtm.addColumn("Fecha de nacimiento");
        dtm.addColumn("Dorsal");
        dtm.addColumn("Posición");
        dtm.addColumn("País");

        datos = BaseDeDatos.getBD().ConsultaSQL("SELECT idJugador, nombre, apellido1, apellido2, fechaNacimiento, dorsal, posicion, pais\n"
                + "FROM jugador");

        if (datos != null) {
            int n = datos.size();
            for (int i = 0; i < n; i++) {
                registro = (String[]) datos.get(i);

                try {
                    Date fecha = formatoBD.parse(registro[4]);
                    registro[4] = formato.format(fecha);
                } catch (ParseException ex) {
                }

                Object[] fila = new Object[]{
                    registro[1],
                    registro[2] + " " + registro[3],
                    registro[4],
                    registro[5],
                    registro[6],
                    registro[7]
                };
                dtm.addRow(fila);
            }
        }

        jTable_Jugadores.setModel(dtm);
    }

    private void masInformacion() {
        String[] registro = (String[]) datos.get(jTable_Jugadores.getSelectedRow());
        id = Integer.parseInt(registro[0]);

        Modificar_Jugador ventana = new Modificar_Jugador((JFrame) this.getRootPane().getParent(), true, id);
        ventana.setTitle("Modificar jugador");
        ventana.setSize(new Dimension(590, 350));
        ventana.setLocationRelativeTo(null);
        ventana.setModal(true);
        ventana.setVisible(true);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel_Jugadores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Jugadores = new javax.swing.JTable();
        jButton_Crear = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_Modificar = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 255, 242));
        setLayout(new java.awt.GridBagLayout());

        jLabel_Jugadores.setBackground(new java.awt.Color(214, 239, 246));
        jLabel_Jugadores.setForeground(new java.awt.Color(44, 123, 156));
        jLabel_Jugadores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Jugadores.setText("Jugadores");
        jLabel_Jugadores.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 16, 8, 0));
        jLabel_Jugadores.setMaximumSize(new java.awt.Dimension(2300, 300));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 8, 8);
        add(jLabel_Jugadores, gridBagConstraints);

        jTable_Jugadores.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable_Jugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Jugadores.setRowHeight(24);
        jTable_Jugadores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_Jugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_JugadoresMouseClicked(evt);
            }
        });
        jTable_Jugadores.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable_JugadoresPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Jugadores);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 16, 16);
        add(jScrollPane1, gridBagConstraints);

        jButton_Crear.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Crear.setText("CREAR NUEVO");
        jButton_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 48, 0);
        add(jButton_Crear, gridBagConstraints);

        jButton_Eliminar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Eliminar.setText("ELIMINAR");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 48, 0);
        add(jButton_Eliminar, gridBagConstraints);

        jButton_Modificar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Modificar.setText("MODIFICAR");
        jButton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 16, 48, 0);
        add(jButton_Modificar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_JugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_JugadoresMouseClicked
        if (evt.getClickCount() == 1) {
            estadoBotones();
        }
        if (evt.getClickCount() == 2) {
            masInformacion();
        }
    }//GEN-LAST:event_jTable_JugadoresMouseClicked

    private void jButton_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearActionPerformed
        Alta_Jugador ventana = new Alta_Jugador((JFrame) this.getRootPane().getParent(), true);
        ventana.setTitle("Nuevo jugador");
        ventana.setSize(new Dimension(590, 350));
        ventana.setLocationRelativeTo(null);
        ventana.setModal(true);
        ventana.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_jButton_CrearActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        String[] registro = (String[]) datos.get(jTable_Jugadores.getSelectedRow());
        id = Integer.parseInt(registro[0]);

        ArrayList numeroEquipos = BaseDeDatos.getBD().ConsultaSQL("SELECT COUNT(*) FROM pertenece WHERE idJugador=" + id);
        registro = (String[]) numeroEquipos.get(0);
        if (Integer.parseInt(registro[0]) > 0) {
            JOptionPane.showMessageDialog(this, "No se puede borrar este jugador porque pertenece a algún equipo.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int respuesta = JOptionPane.showOptionDialog(this, "¿Seguro que quiere eliminar este jugador?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, new Object[]{"SÍ", "NO"}, "NO");
        if (respuesta == 0) {
            datos = BaseDeDatos.getBD().ConsultaSQL("DELETE FROM jugador WHERE idJugador = " + id);
            cargarTabla();
        }
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jButton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarActionPerformed
        masInformacion();
    }//GEN-LAST:event_jButton_ModificarActionPerformed

    private void jTable_JugadoresPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable_JugadoresPropertyChange
        estadoBotones();
    }//GEN-LAST:event_jTable_JugadoresPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Crear;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Modificar;
    private javax.swing.JLabel jLabel_Jugadores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Jugadores;
    // End of variables declaration//GEN-END:variables
}
