/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tfg;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Antonio
 */
public class Ligas extends javax.swing.JPanel {

    /**
     * Creates new form Ligas
     */
    public Ligas() {
        initComponents();
        estiloJLabel();
    }
    
    public void estiloJLabel(){
        jLabel_Ligas.setFont(new Font("Verdana", 0, 50));
        jLabel_Ligas.setOpaque(true);
        jLabel_Ligas.setBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Ligas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Ligas = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Ligas.setBackground(new java.awt.Color(255, 255, 51));
        jLabel_Ligas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Ligas.setText("Ligas");
        jLabel_Ligas.setMaximumSize(new java.awt.Dimension(2300, 300));
        add(jLabel_Ligas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTable_Ligas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Ligas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Ligas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Ligas;
    // End of variables declaration//GEN-END:variables
}
