/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tfg;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import tfg.Alta.Alta_Temporada;

/**
 *
 * @author Antonio
 */
public class Temporadas extends javax.swing.JPanel {

    private class miTablaModel extends DefaultTableModel{
        public boolean isCellEditable (int row, int column){
            return false;
        }
    }
    
    ArrayList datos = null;
    
    int id = -1;
    int anio = -1;
    
    public Temporadas() {
        initComponents();
        cargarTabla();
        estiloJLabel();
        establecerDiseño();
        jButton_Eliminar.setEnabled(false);
    }
    
    public void estiloJLabel(){
        jLabel_Temporadas.setFont(new Font("Verdana", 0, 50));
        jLabel_Temporadas.setOpaque(true);
        jLabel_Temporadas.setBackground(Color.yellow);
    }
    
    public void cargarTabla(){
        String[] registro = null;
        
        miTablaModel dtm = new miTablaModel();
        dtm.addColumn("ID");
        dtm.addColumn("Año");
                
        datos = BaseDeDatos.getBD().ConsultaSQL("SELECT idTemporada, anio FROM temporada");
        
        if(datos != null){
            int n = datos.size();
            for(int i = 0; i < n; i++){
                registro = (String[]) datos.get(i);
                Object[] fila = new Object[]{
                    registro[0],
                    registro[1]
                };
                dtm.addRow(fila); 
            }
        }
        
        jTable_Temporadas.setModel(dtm);
    }
    
    public void establecerDiseño(){
        jButton_Crear.setFont(new java.awt.Font("Microsoft JhengHei", 0, 20));
        //jButton_Continuar.setBackground(Color.WHITE);
        jButton_Crear.setOpaque(true);
        //jButton_Continuar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Crear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Temporadas = new javax.swing.JTable();
        jLabel_Temporadas = new javax.swing.JLabel();
        jButton_Eliminar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Crear.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Crear.setText("CREAR UNA NUEVA");
        jButton_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CrearActionPerformed(evt);
            }
        });
        add(jButton_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        jTable_Temporadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Temporadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_TemporadasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Temporadas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel_Temporadas.setBackground(new java.awt.Color(255, 255, 51));
        jLabel_Temporadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Temporadas.setText("Temporadas");
        jLabel_Temporadas.setMaximumSize(new java.awt.Dimension(2300, 300));
        add(jLabel_Temporadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton_Eliminar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Eliminar.setText("ELIMINAR");
        jButton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarActionPerformed(evt);
            }
        });
        add(jButton_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CrearActionPerformed
        Alta_Temporada ventana =  new Alta_Temporada ((JFrame) this.getRootPane().getParent(), true);
        ventana.setTitle("Nueva temporada");
        ventana.setSize(new Dimension(500, 300));
        ventana.setLocationRelativeTo(null);
        ventana.setModal(true);
        ventana.setVisible(true);
        cargarTabla();
    }//GEN-LAST:event_jButton_CrearActionPerformed

    private void jButton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarActionPerformed
        String[] registro = (String[]) datos.get(jTable_Temporadas.getSelectedRow());
        id = Integer.parseInt(registro[0]);
        datos = BaseDeDatos.getBD().ConsultaSQL("DELETE FROM temporada WHERE idTemporada = '" +id +"'");
        cargarTabla();
    }//GEN-LAST:event_jButton_EliminarActionPerformed

    private void jTable_TemporadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_TemporadasMouseClicked
        if(evt.getClickCount()==1){
            jButton_Eliminar.setEnabled(true);
        }
    }//GEN-LAST:event_jTable_TemporadasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Crear;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JLabel jLabel_Temporadas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Temporadas;
    // End of variables declaration//GEN-END:variables
}
