/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tfg;

import java.awt.Color;

/**
 *
 * @author Antonio
 */
public class Temporadas extends javax.swing.JPanel {

    /**
     * Creates new form Panel1
     */
    public Temporadas() {
        initComponents();
        establecerDiseño();
    }
    
    public void establecerDiseño(){
        jButton_Crear.setFont(new java.awt.Font("Microsoft JhengHei", 0, 20));
        //jButton_Continuar.setBackground(Color.WHITE);
        jButton_Crear.setOpaque(true);
        //jButton_Continuar.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Crear = new javax.swing.JButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jComboBox_Temporadas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton_Continuar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Crear.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Crear.setText("CREAR UNA NUEVA");
        add(jButton_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, -1, -1));

        jLabel_Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_nueva_temporada_1.PNG"))); // NOI18N
        add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 730, 340));

        jComboBox_Temporadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox_Temporadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));

        jLabel2.setText("Cargar temporadas base de datos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        jButton_Continuar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton_Continuar.setText("CONTINUAR");
        add(jButton_Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Continuar;
    private javax.swing.JButton jButton_Crear;
    private javax.swing.JComboBox<String> jComboBox_Temporadas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Titulo;
    // End of variables declaration//GEN-END:variables
}
